<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistical Analysis of Stop and Search Practices on Black Communities in the UK - 5&nbsp; Results</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./discussion.html" rel="next">
<link href="./methodology.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./results.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Results</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Analysis of Stop and Search Practices on Black Communities in the UK</a> 
        <div class="sidebar-tools-main">
    <a href="./Statistical-Analysis-of-Stop-and-Search-Practices-on-Black-Communities-in-the-UK.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statistical Analysis of UK Stop and Search</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Literature Review</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Methodology</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./results.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Results</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discussion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Discussion Section</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title"><strong>Conclusion</strong></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#census-data" id="toc-census-data" class="nav-link active" data-scroll-target="#census-data"><span class="header-section-number">5.1</span> Census data</a>
  <ul class="collapse">
  <li><a href="#ethnic-composition-across-english-regions" id="toc-ethnic-composition-across-english-regions" class="nav-link" data-scroll-target="#ethnic-composition-across-english-regions"><span class="header-section-number">5.1.1</span> Ethnic Composition Across English Regions</a></li>
  <li><a href="#population-distribution-by-ethnic-group-and-region" id="toc-population-distribution-by-ethnic-group-and-region" class="nav-link" data-scroll-target="#population-distribution-by-ethnic-group-and-region"><span class="header-section-number">5.1.2</span> Population Distribution by Ethnic Group and Region</a></li>
  <li><a href="#geographic-distribution-of-the-black-or-black-british-population" id="toc-geographic-distribution-of-the-black-or-black-british-population" class="nav-link" data-scroll-target="#geographic-distribution-of-the-black-or-black-british-population"><span class="header-section-number">5.1.3</span> Geographic Distribution of the Black or Black British Population</a></li>
  </ul></li>
  <li><a href="#stop-and-search-data" id="toc-stop-and-search-data" class="nav-link" data-scroll-target="#stop-and-search-data"><span class="header-section-number">5.2</span> Stop and Search data</a>
  <ul class="collapse">
  <li><a href="#total-stop-and-searches-by-year" id="toc-total-stop-and-searches-by-year" class="nav-link" data-scroll-target="#total-stop-and-searches-by-year"><span class="header-section-number">5.2.1</span> Total Stop and Searches by Year</a></li>
  <li><a href="#disparity-rates-relative-to-white-individuals" id="toc-disparity-rates-relative-to-white-individuals" class="nav-link" data-scroll-target="#disparity-rates-relative-to-white-individuals"><span class="header-section-number">5.2.2</span> Disparity Rates Relative to White Individuals</a></li>
  <li><a href="#outcome-and-link" id="toc-outcome-and-link" class="nav-link" data-scroll-target="#outcome-and-link"><span class="header-section-number">5.2.3</span> Outcome and Link</a></li>
  </ul></li>
  <li><a href="#modelling" id="toc-modelling" class="nav-link" data-scroll-target="#modelling"><span class="header-section-number">5.3</span> Modelling</a>
  <ul class="collapse">
  <li><a href="#overview-of-models-tested" id="toc-overview-of-models-tested" class="nav-link" data-scroll-target="#overview-of-models-tested"><span class="header-section-number">5.3.1</span> <strong>Overview of Models Tested</strong></a></li>
  <li><a href="#key-considerations" id="toc-key-considerations" class="nav-link" data-scroll-target="#key-considerations"><span class="header-section-number">5.3.2</span> <strong>Key Considerations</strong></a></li>
  </ul></li>
  <li><a href="#chosen-model" id="toc-chosen-model" class="nav-link" data-scroll-target="#chosen-model"><span class="header-section-number">5.4</span> Chosen Model</a>
  <ul class="collapse">
  <li><a href="#overview-of-the-poisson-regression" id="toc-overview-of-the-poisson-regression" class="nav-link" data-scroll-target="#overview-of-the-poisson-regression"><span class="header-section-number">5.4.1</span> Overview of the Poisson Regression</a></li>
  <li><a href="#model-results" id="toc-model-results" class="nav-link" data-scroll-target="#model-results"><span class="header-section-number">5.4.2</span> Model results</a></li>
  <li><a href="#model-coefficients-interpretation" id="toc-model-coefficients-interpretation" class="nav-link" data-scroll-target="#model-coefficients-interpretation"><span class="header-section-number">5.4.3</span> Model Coefficients: Interpretation</a></li>
  <li><a href="#model-fit-and-diagnostics" id="toc-model-fit-and-diagnostics" class="nav-link" data-scroll-target="#model-fit-and-diagnostics"><span class="header-section-number">5.4.4</span> Model Fit and Diagnostics</a></li>
  <li><a href="#addressing-the-project-questions" id="toc-addressing-the-project-questions" class="nav-link" data-scroll-target="#addressing-the-project-questions"><span class="header-section-number">5.4.5</span> Addressing the Project Questions</a></li>
  <li><a href="#addressing-the-project-questions-1" id="toc-addressing-the-project-questions-1" class="nav-link" data-scroll-target="#addressing-the-project-questions-1"><span class="header-section-number">5.4.6</span> Addressing the Project Questions</a></li>
  <li><a href="#implications-of-findings" id="toc-implications-of-findings" class="nav-link" data-scroll-target="#implications-of-findings"><span class="header-section-number">5.4.7</span> Implications of Findings</a></li>
  <li><a href="#policy-implications" id="toc-policy-implications" class="nav-link" data-scroll-target="#policy-implications"><span class="header-section-number">5.4.8</span> Policy Implications</a></li>
  </ul></li>
  <li><a href="#random-forest-model-machine-learning-approach" id="toc-random-forest-model-machine-learning-approach" class="nav-link" data-scroll-target="#random-forest-model-machine-learning-approach"><span class="header-section-number">5.5</span> Random Forest Model: Machine Learning Approach</a>
  <ul class="collapse">
  <li><a href="#variable-importance-and-interpretation" id="toc-variable-importance-and-interpretation" class="nav-link" data-scroll-target="#variable-importance-and-interpretation"><span class="header-section-number">5.5.1</span> Variable Importance and Interpretation</a></li>
  <li><a href="#implications-for-project-objectives" id="toc-implications-for-project-objectives" class="nav-link" data-scroll-target="#implications-for-project-objectives"><span class="header-section-number">5.5.2</span> Implications for Project Objectives</a></li>
  </ul></li>
  <li><a href="#sec-trend" id="toc-sec-trend" class="nav-link" data-scroll-target="#sec-trend"><span class="header-section-number">5.6</span> Five-Year Disparity Trend</a></li>
  <li><a href="#sec-regional" id="toc-sec-regional" class="nav-link" data-scroll-target="#sec-regional"><span class="header-section-number">5.7</span> Regional Force Rankings</a></li>
  <li><a href="#sec-outcomes" id="toc-sec-outcomes" class="nav-link" data-scroll-target="#sec-outcomes"><span class="header-section-number">5.8</span> Outcome Disparity by Ethnicity</a></li>
  <li><a href="#sec-age-ethnicity" id="toc-sec-age-ethnicity" class="nav-link" data-scroll-target="#sec-age-ethnicity"><span class="header-section-number">5.9</span> Age by Ethnicity Interaction</a></li>
  <li><a href="#sec-reason-skew" id="toc-sec-reason-skew" class="nav-link" data-scroll-target="#sec-reason-skew"><span class="header-section-number">5.10</span> Racial Skew by Search Reason</a></li>
  <li><a href="#sec-missing" id="toc-sec-missing" class="nav-link" data-scroll-target="#sec-missing"><span class="header-section-number">5.11</span> Missing Ethnicity Data: Systematic Patterns</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Results</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The results presented in this section provide a comprehensive analysis of stop-and-search data in England and Wales. Leveraging both descriptive statistics and advanced statistical models, we explore the key patterns, disparities, and trends in stop-and-search practices across demographic, geographic, and temporal dimensions. The findings highlight significant disproportionalities in stop-and-search rates among ethnic groups, with a particular focus on the Black or Black British population. Additionally, the results provide insights into the influence of factors such as age, sex, region, and reason for search on stop-and-search frequencies. This section concludes with the application of machine learning techniques, specifically random forests, to uncover additional patterns and establish a framework for prediction.</p>
<section id="census-data" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="census-data"><span class="header-section-number">5.1</span> Census data</h2>
<p>The analysis of census data provides critical insights into the demographic composition of England and Wales. This section examines the distribution of ethnic groups across English regions, highlighting variations in population proportions and regional disparities. The results form the basis for understanding broader demographic patterns that intersect with stop-and-search practices. Key metrics such as mean percentages, standard deviations, and ranges are calculated to quantify these distributions and inform subsequent analyses.</p>
<section id="ethnic-composition-across-english-regions" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="ethnic-composition-across-english-regions"><span class="header-section-number">5.1.1</span> Ethnic Composition Across English Regions</h3>
<p>The table below summarizes the composition of ethnic groups across English regions, showing the mean percentage, standard deviation (SD), and range (minimum to maximum) for each group. This provides an overview of the variability in ethnic group proportions across regions.</p>
<div>
<table class="table" data-quarto-postprocess="true">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Ethnic Group Composition Across English Regions (%)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Ethnic Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Asian or Asian British</td>
<td style="text-align: right;">8.2</td>
<td style="text-align: right;">5.4</td>
<td style="text-align: right;">2.8</td>
<td style="text-align: right;">20.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Black or Black British</td>
<td style="text-align: right;">3.4</td>
<td style="text-align: right;">3.7</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">13.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mixed</td>
<td style="text-align: right;">2.6</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">5.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other Ethnic Group</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">6.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">White</td>
<td style="text-align: right;">84.0</td>
<td style="text-align: right;">11.8</td>
<td style="text-align: right;">53.8</td>
<td style="text-align: right;">93.8</td>
</tr>
</tbody>
</table>


</div>
<p>The data highlights significant disparities between ethnic groups. Notably, the average proportion of individuals identifying as Black or Black British is 3.4%, with regional variation ranging from 0.9% to 13.5%. In contrast, the White group, which has the largest mean proportion at 84%, also shows variability, ranging from 53.8% to 93.8%. These patterns underline the diverse ethnic composition across regions, particularly the stark contrast between Black and White populations.</p>
</section>
<section id="population-distribution-by-ethnic-group-and-region" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="population-distribution-by-ethnic-group-and-region"><span class="header-section-number">5.1.2</span> Population Distribution by Ethnic Group and Region</h3>
<p>The table below summarizes the total population distribution by ethnic group across regions in England and Wales, based on census data. Population counts are presented in thousands, providing a clear view of regional demographics. The summary includes total counts for each ethnic group and highlights regional variations, which are key to understanding the geographic diversity of the population.</p>
<div>
<div class="table-responsive">
<table class="table table-striped" data-quarto-postprocess="true">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Total Population by Ethnic Group and Region (per 1,000)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">region</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Asian or Asian British</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Black or Black British</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mixed</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Other Ethnic Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">White</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 3cm;">East Midlands</td>
<td style="text-align: right;">391.1</td>
<td style="text-align: right;">130.0</td>
<td style="text-align: right;">117.2</td>
<td style="text-align: right;">61.9</td>
<td style="text-align: right;">4179.8</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3cm;">Eastern</td>
<td style="text-align: right;">405.9</td>
<td style="text-align: right;">185.0</td>
<td style="text-align: right;">179.7</td>
<td style="text-align: right;">86.2</td>
<td style="text-align: right;">5478.4</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 3cm;">London</td>
<td style="text-align: right;">1817.6</td>
<td style="text-align: right;">1188.4</td>
<td style="text-align: right;">505.8</td>
<td style="text-align: right;">556.8</td>
<td style="text-align: right;">4731.2</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3cm;">North East</td>
<td style="text-align: right;">98.0</td>
<td style="text-align: right;">26.6</td>
<td style="text-align: right;">33.3</td>
<td style="text-align: right;">26.3</td>
<td style="text-align: right;">2462.7</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 3cm;">North West</td>
<td style="text-align: right;">622.7</td>
<td style="text-align: right;">173.9</td>
<td style="text-align: right;">163.3</td>
<td style="text-align: right;">110.2</td>
<td style="text-align: right;">6347.4</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3cm;">South East</td>
<td style="text-align: right;">650.5</td>
<td style="text-align: right;">221.6</td>
<td style="text-align: right;">260.9</td>
<td style="text-align: right;">135.7</td>
<td style="text-align: right;">8009.4</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 3cm;">South West</td>
<td style="text-align: right;">159.2</td>
<td style="text-align: right;">69.6</td>
<td style="text-align: right;">114.1</td>
<td style="text-align: right;">48.7</td>
<td style="text-align: right;">5309.6</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3cm;">Wales</td>
<td style="text-align: right;">89.0</td>
<td style="text-align: right;">27.6</td>
<td style="text-align: right;">48.6</td>
<td style="text-align: right;">26.5</td>
<td style="text-align: right;">2915.9</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 3cm;">West Midlands</td>
<td style="text-align: right;">794.3</td>
<td style="text-align: right;">269.0</td>
<td style="text-align: right;">178.2</td>
<td style="text-align: right;">124.2</td>
<td style="text-align: right;">4585.0</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3cm;">Yorkshire and the Humber</td>
<td style="text-align: right;">487.1</td>
<td style="text-align: right;">117.6</td>
<td style="text-align: right;">117.0</td>
<td style="text-align: right;">79.1</td>
<td style="text-align: right;">4680.0</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; width: 3cm;">Total</td>
<td style="text-align: right; font-weight: bold;">5515.4</td>
<td style="text-align: right; font-weight: bold;">2409.3</td>
<td style="text-align: right; font-weight: bold;">1718.1</td>
<td style="text-align: right; font-weight: bold;">1255.6</td>
<td style="text-align: right; font-weight: bold;">48699.4</td>
</tr>
</tbody>
</table>
</div>


</div>
<p>The census data reveals that the total population of individuals identifying as Black or Black British across all regions is 2,409 thousand, compared to 48,699 thousand for the White group. In London, which has the highest concentration of Black or Black British individuals among all regions, this group accounts for 1,188 thousand, while the White population in London is 4,731 thousand.</p>
<p>The region with the largest White population is South East, while London has the highest Black or Black British population outside London. These figures highlight the substantial geographic and demographic diversity captured in the census data.</p>
</section>
<section id="geographic-distribution-of-the-black-or-black-british-population" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="geographic-distribution-of-the-black-or-black-british-population"><span class="header-section-number">5.1.3</span> Geographic Distribution of the Black or Black British Population</h3>
<p>The map below visualizes the geographic distribution of individuals identifying as Black or Black British across regions in the UK, based on census data. It represents the proportion of this ethnic group within each region as a percentage of the total regional population, highlighting spatial patterns and regional disparities.</p>
<p><img src="results_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
<p>The map illustrates substantial regional variability in the proportion of individuals identifying as Black or Black British. The region with the highest proportion is London, where this group accounts for 13.5% of the total population. In contrast, the region with the lowest proportion is Wales, at just 0.9%.</p>
<p>These results emphasize the uneven distribution of the Black population across the UK, reflecting broader patterns of settlement, migration, and urbanization.</p>
</section>
</section>
<section id="stop-and-search-data" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="stop-and-search-data"><span class="header-section-number">5.2</span> Stop and Search data</h2>
<p>This section examines police stop and search activities across England and Wales. This data includes searches conducted under key legislations, specifically Section 1 of the Police and Criminal Evidence Act (PACE) and Section 60 of the Criminal Justice and Public Order Act (CJPOA). By analyzing annual trends, legislative frameworks, and demographic characteristics, this section aims to provide insights into the scale and patterns of stop and search practices. The results inform subsequent analyses of disparities and contributing factors.</p>
<section id="total-stop-and-searches-by-year" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="total-stop-and-searches-by-year"><span class="header-section-number">5.2.1</span> Total Stop and Searches by Year</h3>
<p>The table below details the annual total of stop and searches conducted in England and Wales under Section 1 of the Police and Criminal Evidence Act (PACE) and Section 60 of the Criminal Justice and Public Order Act (CJPOA). This summary highlights year-on-year trends and the overall scale of these police powers.</p>
<div>
<table class="table" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Total Stop and Searches Conducted in England and Wales by Financial Year
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Financial Year</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Total Searches</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2020/21</td>
<td style="text-align: left;">714,914</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021/22</td>
<td style="text-align: left;">530,970</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022/23</td>
<td style="text-align: left;">547,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">2023/24</td>
<td style="text-align: left;">536,151</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024/25</td>
<td style="text-align: left;">528,242</td>
</tr>
</tbody>
</table>


</div>
<p>The data shows that the highest number of stop and searches was conducted in the financial year 2020/21, with a total of 714,914 searches. In contrast, the financial year with the lowest number of searches was 2024/25, with 528,242 searches.</p>
<p>These figures reflect changes in policing strategies and legal contexts, as well as broader socio-political factors influencing the use of stop and search powers over time.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Analysis sample vs.&nbsp;published totals
</div>
</div>
<div class="callout-body-container callout-body">
<p>The totals above match the figures published by the UK Government and include <em>all</em> recorded stop and searches under PACE s.1 and CJPOA s.60. The disparity analysis presented in the rest of this report uses a smaller <strong>analysis sample</strong> that excludes three categories of records that cannot be assigned to a demographic group or geographic denominator (see <a href="methodology.html#sec-data-processing" class="quarto-xref"><span>Section 4.3</span></a> for details):</p>
<ol type="1">
<li><strong>Vehicle searches</strong>: no person-level demographics are recorded.</li>
<li><strong>British Transport Police (region 0)</strong>: no Census population denominator exists for BTP.</li>
<li><strong>“Not Stated” ethnicity</strong>:these records cannot be attributed to any ethnic group for rate calculations.</li>
</ol>
<div>
<table class="table" data-quarto-postprocess="true">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Reconciliation of Published Totals and Analysis Sample
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Financial Year</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Published Total</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Analysis Sample</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Excluded</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">% Retained</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2020/21</td>
<td style="text-align: left;">714,914</td>
<td style="text-align: left;">555,915</td>
<td style="text-align: left;">158,999</td>
<td style="text-align: right;">77.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021/22</td>
<td style="text-align: left;">530,970</td>
<td style="text-align: left;">405,946</td>
<td style="text-align: left;">125,024</td>
<td style="text-align: right;">76.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022/23</td>
<td style="text-align: left;">547,000</td>
<td style="text-align: left;">411,353</td>
<td style="text-align: left;">135,647</td>
<td style="text-align: right;">75.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">2023/24</td>
<td style="text-align: left;">536,151</td>
<td style="text-align: left;">404,636</td>
<td style="text-align: left;">131,515</td>
<td style="text-align: right;">75.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024/25</td>
<td style="text-align: left;">528,242</td>
<td style="text-align: left;">402,376</td>
<td style="text-align: left;">125,866</td>
<td style="text-align: right;">76.2</td>
</tr>
</tbody>
</table>


</div>
<p>The analysis sample retains approximately 76% of all searches across years. All disparity rates, IRRs, and dashboard figures are based on this analysis sample.</p>
</div>
</div>
<p>Note that the stop and search dataset contains some missing data, primarily in the <code>officer_defined_ethnicity</code> variable. Other missing values occur because certain searches were related to vehicles, which are not included in this analysis. As a result, the percentage of truly missing data in the original dataset is 4.6%. These missing values were handled appropriately to ensure robust analysis.</p>
</section>
<section id="disparity-rates-relative-to-white-individuals" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="disparity-rates-relative-to-white-individuals"><span class="header-section-number">5.2.2</span> Disparity Rates Relative to White Individuals</h3>
<p>The table below presents disparity rates for stop and searches relative to White individuals across different financial years. Disparity rates indicate how much more (or less) likely individuals from other ethnic groups are to be stopped and searched compared to White individuals. These rates are derived by comparing the stop-and-search rate per population for each ethnic group against the rate for White individuals.</p>
<div>
<table class="table" data-quarto-postprocess="true">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Disparity rates relative to White individuals,<br>
by financial year
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Financial Year</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Asian or Asian British</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Black or Black British</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mixed</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Other Ethnic Group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2020/21</td>
<td style="text-align: right;">1.85</td>
<td style="text-align: right;">5.49</td>
<td style="text-align: right;">1.67</td>
<td style="text-align: right;">1.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021/22</td>
<td style="text-align: right;">1.59</td>
<td style="text-align: right;">4.81</td>
<td style="text-align: right;">1.67</td>
<td style="text-align: right;">1.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022/23</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: right;">4.08</td>
<td style="text-align: right;">1.64</td>
<td style="text-align: right;">1.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">2023/24</td>
<td style="text-align: right;">1.34</td>
<td style="text-align: right;">3.62</td>
<td style="text-align: right;">1.62</td>
<td style="text-align: right;">1.35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024/25</td>
<td style="text-align: right;">1.39</td>
<td style="text-align: right;">3.65</td>
<td style="text-align: right;">1.74</td>
<td style="text-align: right;">1.47</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Average</td>
<td style="text-align: right; font-weight: bold;">1.52</td>
<td style="text-align: right; font-weight: bold;">4.33</td>
<td style="text-align: right; font-weight: bold;">1.67</td>
<td style="text-align: right; font-weight: bold;">1.31</td>
</tr>
</tbody>
</table>


</div>
<p>The data reveals that individuals identifying as Black or Black British consistently experience the highest disparity rates in stop and searches compared to White individuals. The highest disparity was recorded in 2020/21, with a relative rate of 5.49, while the lowest disparity occurred in 2023/24, at 3.62. On average, the disparity rate for this group across all financial years is 4.33.</p>
<p>These figures underscore the significant disparities faced by Black individuals in stop and search practices. Similar trends are observed for other ethnic groups, though with lower disparity rates compared to the Black or Black British group.</p>
<p>The most recent year, 2024/25, yields a Black/White disparity rate of <strong>3.6×</strong> (from 3.65). This is the unadjusted figure, calculated directly from search counts divided by Census 2021 population denominators with no covariates controlled,d is the number shown on the interactive dashboard. The adjusted incidence rate ratio from the Poisson model (see <a href="#sec-trend" class="quarto-xref"><span>Section 5.6</span></a>) is lower because the model accounts for differences in regional composition, sex, age, and search type across ethnic groups; the gap between the two measures reflects those compositional differences rather than any inconsistency in the data.</p>
</section>
<section id="outcome-and-link" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="outcome-and-link"><span class="header-section-number">5.2.3</span> Outcome and Link</h3>
<p>The question we want to investigate here is whether stop and search results in successful motives. We have removed “Unknown link” and “Unknown whether article found.” Then, we create a new column called “success” - if link is “Linked,” it is successful, otherwise, it is not.</p>
<p>The overall success ratio is: 34.5%.</p>
</section>
</section>
<section id="modelling" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="modelling"><span class="header-section-number">5.3</span> Modelling</h2>
<p>This section outlines the statistical modelling approach applied to analyze stop and search data. Multiple models were constructed and evaluated, each targeting specific aspects of the data while considering methodological rigor. The focus was on understanding disparities across financial years, regions, and ethnic groups, controlling for key covariates such as sex, age group, and reason for search.</p>
<section id="overview-of-models-tested" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="overview-of-models-tested"><span class="header-section-number">5.3.1</span> <strong>Overview of Models Tested</strong></h3>
<ol type="1">
<li><strong>Model 1: Simple Linear Regression</strong>
<ul>
<li>A baseline linear regression model was fitted with the stop-and-search rate (<code>rate</code>) as the dependent variable.</li>
<li>Independent variables included financial year, region, ethnicity, sex, age group, and reason for search.</li>
<li>Diagnostics revealed significant heteroscedasticity, making this model unsuitable.</li>
</ul></li>
<li><strong>Model 2: Log-Transformed Linear Regression</strong>
<ul>
<li>To address heteroscedasticity, a logarithmic transformation of the rate (<code>log(rate)</code>) was applied.</li>
<li>The transformed model demonstrated improved fit and approximate normality in residuals.</li>
</ul></li>
<li><strong>Mixed Linear Model</strong>
<ul>
<li>A mixed-effects model was considered, treating financial year as a random effect to account for potential year-specific variability.</li>
<li>However, the random effect’s variance was close to zero, indicating that this added complexity was unnecessary.</li>
</ul></li>
<li><strong>Generalized Linear Model (GLM) with Offset</strong>
<ul>
<li>A Poisson GLM with a log link function was employed, using the number of searches as the dependent variable and the log population as an offset.</li>
<li>This model was particularly relevant for adjusting for population size across regions and demographics.</li>
<li>All parameters were highly significant (<code>p &lt; 0.0001</code>), and the effect sizes for ethnic groups were consistent with findings from prior research.</li>
</ul></li>
<li><strong>Model Evaluation</strong>
<ul>
<li>Pseudo-R² by Cohen was used to assess the GLM’s fit. The pseudo-R² value confirmed the model’s adequacy for explaining variability in the data.</li>
</ul></li>
</ol>
</section>
<section id="key-considerations" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="key-considerations"><span class="header-section-number">5.3.2</span> <strong>Key Considerations</strong></h3>
<ul>
<li><strong>Model Selection</strong>: While multiple models were tested, the GLM with an offset was identified as the most appropriate for the dataset, balancing interpretability and statistical validity.</li>
<li><strong>Diagnostics</strong>: Each model was assessed for assumptions such as normality of residuals, heteroscedasticity, and random effects variance to ensure robustness.</li>
<li><strong>Significance of Covariates</strong>: Across models, ethnicity consistently emerged as a significant factor, supporting the focus on disparities in stop-and-search practices.</li>
</ul>
<p>These models provide a robust framework for understanding patterns and disparities in stop-and-search data, and they form the foundation for further statistical and interpretive analysis.</p>
<p>Based on the results of the evaluated models, a Poisson regression with a population offset was selected as the final model. The following section delves into the rationale, structure, and key findings of the chosen model.</p>
</section>
</section>
<section id="chosen-model" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="chosen-model"><span class="header-section-number">5.4</span> Chosen Model</h2>
<section id="overview-of-the-poisson-regression" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="overview-of-the-poisson-regression"><span class="header-section-number">5.4.1</span> Overview of the Poisson Regression</h3>
<p>The Poisson regression model with an offset for population size was selected as the most appropriate approach for this analysis. This model accounts for varying population sizes across regions, allowing for a fair comparison of stop-and-search rates. The dependent variable is the total number of stop and searches, with independent variables including financial year, region, ethnicity, sex, age group, and reason for search. Reference levels for categorical variables are:</p>
<ul>
<li>Financial Year: 2020/21</li>
<li>Region: East Midlands</li>
<li>Ethnicity: White</li>
<li>Sex: Female</li>
<li>Age Group: 25 and above</li>
<li>Reason for Search: Non-drug-related</li>
</ul>
</section>
<section id="model-results" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="model-results"><span class="header-section-number">5.4.2</span> Model results</h3>
<p>The table below summarizes the results of the Poisson regression model analyzing the frequency of stop and searches across England and Wales. The raw coefficients from the model (log-scale) provide statistical estimates for the association between each variable and the expected log count of stop and searches.</p>
<p>However, for ease of interpretation, these coefficients are exponentiated to present rate ratios, which quantify the multiplicative effect of each variable relative to the baseline categories. For instance, a rate ratio greater than 1 indicates a higher likelihood of stop and searches compared to the baseline category, while a rate ratio less than 1 indicates a lower likelihood. Baseline levels for the categorical variables are: financial year <strong>2020/21</strong>, region <strong>East Midlands</strong>, ethnicity <strong>White</strong>, sex <strong>Female</strong>, age group <strong>25 and above</strong>, and reason for search <strong>non-drug-related</strong>.</p>
<p>The following tables first present the raw coefficients for statistical rigor, followed by the exponentiated coefficients (rate ratios) for practical interpretation.</p>
<section id="table-code-raw-coefficients" class="level4" data-number="5.4.2.1">
<h4 data-number="5.4.2.1" class="anchored" data-anchor-id="table-code-raw-coefficients"><span class="header-section-number">5.4.2.1</span> Table Code: Raw Coefficients</h4>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Raw Coefficients from Quasi-Poisson Regression Model
</caption>
<thead>
<tr>
<th style="text-align:left;">
Term
</th>
<th style="text-align:right;">
Log Coefficient
</th>
<th style="text-align:right;">
Std Error
</th>
<th style="text-align:right;">
Z
</th>
<th style="text-align:right;">
P-Value
</th>
<th style="text-align:right;">
Lower CI
</th>
<th style="text-align:right;">
Upper CI
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
-9.524
</td>
<td style="text-align:right;">
0.0602099
</td>
<td style="text-align:right;">
-158.174323
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-9.643
</td>
<td style="text-align:right;">
-9.407
</td>
</tr>
<tr>
<td style="text-align:left;">
financial_year2021/22
</td>
<td style="text-align:right;">
-0.319
</td>
<td style="text-align:right;">
0.0282388
</td>
<td style="text-align:right;">
-11.306597
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-0.375
</td>
<td style="text-align:right;">
-0.264
</td>
</tr>
<tr>
<td style="text-align:left;">
financial_year2022/23
</td>
<td style="text-align:right;">
-0.307
</td>
<td style="text-align:right;">
0.0281390
</td>
<td style="text-align:right;">
-10.915751
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-0.362
</td>
<td style="text-align:right;">
-0.252
</td>
</tr>
<tr>
<td style="text-align:left;">
financial_year2023/24
</td>
<td style="text-align:right;">
-0.332
</td>
<td style="text-align:right;">
0.0283447
</td>
<td style="text-align:right;">
-11.723599
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-0.388
</td>
<td style="text-align:right;">
-0.277
</td>
</tr>
<tr>
<td style="text-align:left;">
financial_year2024/25
</td>
<td style="text-align:right;">
-0.365
</td>
<td style="text-align:right;">
0.0286146
</td>
<td style="text-align:right;">
-12.740845
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-0.421
</td>
<td style="text-align:right;">
-0.309
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanEast of England
</td>
<td style="text-align:right;">
0.436
</td>
<td style="text-align:right;">
0.0601634
</td>
<td style="text-align:right;">
7.254569
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.319
</td>
<td style="text-align:right;">
0.555
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanLondon
</td>
<td style="text-align:right;">
1.409
</td>
<td style="text-align:right;">
0.0525822
</td>
<td style="text-align:right;">
26.801986
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
1.308
</td>
<td style="text-align:right;">
1.514
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanNorth East
</td>
<td style="text-align:right;">
0.618
</td>
<td style="text-align:right;">
0.0702577
</td>
<td style="text-align:right;">
8.793727
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.480
</td>
<td style="text-align:right;">
0.756
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanNorth West
</td>
<td style="text-align:right;">
1.374
</td>
<td style="text-align:right;">
0.0531494
</td>
<td style="text-align:right;">
25.854011
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
1.271
</td>
<td style="text-align:right;">
1.480
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanSouth East
</td>
<td style="text-align:right;">
0.361
</td>
<td style="text-align:right;">
0.0575411
</td>
<td style="text-align:right;">
6.280358
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.250
</td>
<td style="text-align:right;">
0.475
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanSouth West
</td>
<td style="text-align:right;">
-0.091
</td>
<td style="text-align:right;">
0.0691195
</td>
<td style="text-align:right;">
-1.310296
</td>
<td style="text-align:right;">
0.190
</td>
<td style="text-align:right;">
-0.226
</td>
<td style="text-align:right;">
0.045
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanWales
</td>
<td style="text-align:right;">
0.654
</td>
<td style="text-align:right;">
0.0670340
</td>
<td style="text-align:right;">
9.752562
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.523
</td>
<td style="text-align:right;">
0.785
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanWest Midlands
</td>
<td style="text-align:right;">
0.369
</td>
<td style="text-align:right;">
0.0611492
</td>
<td style="text-align:right;">
6.027697
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.249
</td>
<td style="text-align:right;">
0.489
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanYorkshire and The Humber
</td>
<td style="text-align:right;">
0.649
</td>
<td style="text-align:right;">
0.0596301
</td>
<td style="text-align:right;">
10.883978
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.533
</td>
<td style="text-align:right;">
0.767
</td>
</tr>
<tr>
<td style="text-align:left;">
ethnicityAsian
</td>
<td style="text-align:right;">
0.156
</td>
<td style="text-align:right;">
0.0306058
</td>
<td style="text-align:right;">
5.105050
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.096
</td>
<td style="text-align:right;">
0.216
</td>
</tr>
<tr>
<td style="text-align:left;">
ethnicityBlack
</td>
<td style="text-align:right;">
1.106
</td>
<td style="text-align:right;">
0.0290505
</td>
<td style="text-align:right;">
38.068460
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
1.049
</td>
<td style="text-align:right;">
1.163
</td>
</tr>
<tr>
<td style="text-align:left;">
ethnicityMixed
</td>
<td style="text-align:right;">
0.306
</td>
<td style="text-align:right;">
0.0488384
</td>
<td style="text-align:right;">
6.256767
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.209
</td>
<td style="text-align:right;">
0.400
</td>
</tr>
<tr>
<td style="text-align:left;">
ethnicityOther
</td>
<td style="text-align:right;">
-0.069
</td>
<td style="text-align:right;">
0.0635000
</td>
<td style="text-align:right;">
-1.079808
</td>
<td style="text-align:right;">
0.280
</td>
<td style="text-align:right;">
-0.195
</td>
<td style="text-align:right;">
0.054
</td>
</tr>
<tr>
<td style="text-align:left;">
sexMale
</td>
<td style="text-align:right;">
2.080
</td>
<td style="text-align:right;">
0.0296314
</td>
<td style="text-align:right;">
70.190904
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
2.022
</td>
<td style="text-align:right;">
2.138
</td>
</tr>
<tr>
<td style="text-align:left;">
age_under25Under 25
</td>
<td style="text-align:right;">
0.025
</td>
<td style="text-align:right;">
0.0186159
</td>
<td style="text-align:right;">
1.361190
</td>
<td style="text-align:right;">
0.174
</td>
<td style="text-align:right;">
-0.011
</td>
<td style="text-align:right;">
0.062
</td>
</tr>
<tr>
<td style="text-align:left;">
reason_drugsDrugs
</td>
<td style="text-align:right;">
0.573
</td>
<td style="text-align:right;">
0.0193849
</td>
<td style="text-align:right;">
29.577409
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.535
</td>
<td style="text-align:right;">
0.611
</td>
</tr>
</tbody>
</table>
</section>
<section id="table-code-exponentiated-coefficients-rate-ratios" class="level4" data-number="5.4.2.2">
<h4 data-number="5.4.2.2" class="anchored" data-anchor-id="table-code-exponentiated-coefficients-rate-ratios"><span class="header-section-number">5.4.2.2</span> Table Code: Exponentiated Coefficients (Rate Ratios)</h4>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Exponentiated Coefficients (Incidence Rate Ratios) with 95% CIs
</caption>
<thead>
<tr>
<th style="text-align:left;">
Term
</th>
<th style="text-align:right;">
Rate Ratio
</th>
<th style="text-align:right;">
Lower 95% CI
</th>
<th style="text-align:right;">
Upper 95% CI
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
financial_year2021/22
</td>
<td style="text-align:right;">
0.727
</td>
<td style="text-align:right;">
0.687
</td>
<td style="text-align:right;">
0.768
</td>
</tr>
<tr>
<td style="text-align:left;">
financial_year2022/23
</td>
<td style="text-align:right;">
0.736
</td>
<td style="text-align:right;">
0.696
</td>
<td style="text-align:right;">
0.777
</td>
</tr>
<tr>
<td style="text-align:left;">
financial_year2023/24
</td>
<td style="text-align:right;">
0.717
</td>
<td style="text-align:right;">
0.678
</td>
<td style="text-align:right;">
0.758
</td>
</tr>
<tr>
<td style="text-align:left;">
financial_year2024/25
</td>
<td style="text-align:right;">
0.694
</td>
<td style="text-align:right;">
0.657
</td>
<td style="text-align:right;">
0.734
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanEast of England
</td>
<td style="text-align:right;">
1.547
</td>
<td style="text-align:right;">
1.376
</td>
<td style="text-align:right;">
1.742
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanLondon
</td>
<td style="text-align:right;">
4.093
</td>
<td style="text-align:right;">
3.697
</td>
<td style="text-align:right;">
4.544
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanNorth East
</td>
<td style="text-align:right;">
1.855
</td>
<td style="text-align:right;">
1.616
</td>
<td style="text-align:right;">
2.129
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanNorth West
</td>
<td style="text-align:right;">
3.952
</td>
<td style="text-align:right;">
3.565
</td>
<td style="text-align:right;">
4.391
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanSouth East
</td>
<td style="text-align:right;">
1.435
</td>
<td style="text-align:right;">
1.283
</td>
<td style="text-align:right;">
1.608
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanSouth West
</td>
<td style="text-align:right;">
0.913
</td>
<td style="text-align:right;">
0.798
</td>
<td style="text-align:right;">
1.046
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanWales
</td>
<td style="text-align:right;">
1.923
</td>
<td style="text-align:right;">
1.686
</td>
<td style="text-align:right;">
2.193
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanWest Midlands
</td>
<td style="text-align:right;">
1.446
</td>
<td style="text-align:right;">
1.283
</td>
<td style="text-align:right;">
1.631
</td>
</tr>
<tr>
<td style="text-align:left;">
region_cleanYorkshire and The Humber
</td>
<td style="text-align:right;">
1.914
</td>
<td style="text-align:right;">
1.704
</td>
<td style="text-align:right;">
2.153
</td>
</tr>
<tr>
<td style="text-align:left;">
ethnicityAsian
</td>
<td style="text-align:right;">
1.169
</td>
<td style="text-align:right;">
1.101
</td>
<td style="text-align:right;">
1.241
</td>
</tr>
<tr>
<td style="text-align:left;">
ethnicityBlack
</td>
<td style="text-align:right;">
3.022
</td>
<td style="text-align:right;">
2.854
</td>
<td style="text-align:right;">
3.198
</td>
</tr>
<tr>
<td style="text-align:left;">
ethnicityMixed
</td>
<td style="text-align:right;">
1.357
</td>
<td style="text-align:right;">
1.232
</td>
<td style="text-align:right;">
1.492
</td>
</tr>
<tr>
<td style="text-align:left;">
ethnicityOther
</td>
<td style="text-align:right;">
0.934
</td>
<td style="text-align:right;">
0.823
</td>
<td style="text-align:right;">
1.055
</td>
</tr>
<tr>
<td style="text-align:left;">
sexMale
</td>
<td style="text-align:right;">
8.003
</td>
<td style="text-align:right;">
7.555
</td>
<td style="text-align:right;">
8.486
</td>
</tr>
<tr>
<td style="text-align:left;">
age_under25Under 25
</td>
<td style="text-align:right;">
1.026
</td>
<td style="text-align:right;">
0.989
</td>
<td style="text-align:right;">
1.064
</td>
</tr>
<tr>
<td style="text-align:left;">
reason_drugsDrugs
</td>
<td style="text-align:right;">
1.774
</td>
<td style="text-align:right;">
1.708
</td>
<td style="text-align:right;">
1.843
</td>
</tr>
</tbody>
</table>
</section>
<section id="key-findings" class="level4" data-number="5.4.2.3">
<h4 data-number="5.4.2.3" class="anchored" data-anchor-id="key-findings"><span class="header-section-number">5.4.2.3</span> Key Findings</h4>
<p>The results show significant disparities in stop-and-search likelihoods. For instance, individuals identifying as <strong>Black or Black British</strong> are 3.02 times more likely to be stopped and searched compared to <strong>White</strong> individuals, with a 95% confidence interval of (2.85, 3.2). Similarly, <strong>males</strong> are 8 times more likely to be stopped and searched than females, highlighting a significant gender disparity.</p>
<p><strong>London</strong> stands out with the highest regional rate: individuals there are 4.09 times as likely to be stopped and searched as those in the East Midlands (95% CI: 3.7–4.54).</p>
<p>These findings underscore critical disparities in stop-and-search practices across demographic and geographic dimensions.</p>
</section>
</section>
<section id="model-coefficients-interpretation" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="model-coefficients-interpretation"><span class="header-section-number">5.4.3</span> Model Coefficients: Interpretation</h3>
<p>This analysis evaluates the association between demographic, temporal, and geographic factors and police stop-and-search frequencies in England and Wales using a Poisson regression model. The model includes an offset for population size to account for differences in regional populations, providing rate ratios for stop-and-search frequencies across groups.</p>
<p>Key variables were encoded for interpretability: <strong>age group</strong> was binary, with “Under 25” for individuals aged 10–24 and “25 and over” for those 25 and above; <strong>reason for search</strong> was binary, with “Drugs” for drug-related stops and “Non-drugs” for other reasons. Baseline levels for categorical variables include: financial year <strong>2020/21</strong>, region <strong>East Midlands</strong>, ethnicity <strong>White</strong>, sex <strong>Female</strong>, age group <strong>25 and above</strong>, and reason for search <strong>non-drug-related</strong>. All coefficients are exponentiated to represent rate ratios.</p>
<p>Each rate ratio indicates the multiplicative effect of a variable on the likelihood of stop and search, relative to the baseline. Values greater than 1 represent increased likelihood, while values below 1 signify decreased likelihood.</p>
<section id="coefficients-and-interpretations" class="level4" data-number="5.4.3.1">
<h4 data-number="5.4.3.1" class="anchored" data-anchor-id="coefficients-and-interpretations"><span class="header-section-number">5.4.3.1</span> Coefficients and Interpretations</h4>
<section id="financial-year" class="level5" data-number="5.4.3.1.1">
<h5 data-number="5.4.3.1.1" class="anchored" data-anchor-id="financial-year"><span class="header-section-number">5.4.3.1.1</span> <strong>Financial Year</strong></h5>
<ul>
<li><strong>2021/22</strong>: The rate ratio for <strong>2021/22</strong> is 0.73 (95% CI: 0.69–0.77), indicating that stop-and-search frequencies were approximately 0.73 times as likely compared to <strong>2020/21</strong>.</li>
<li><strong>2022/23</strong>: The rate ratio for <strong>2022/23</strong> is 0.74 (95% CI: 0.7–0.78).</li>
</ul>
<p>These results suggest a consistent decrease in stop-and-search activities over time.</p>
</section>
<section id="region-relative-to-east-midlands" class="level5" data-number="5.4.3.1.2">
<h5 data-number="5.4.3.1.2" class="anchored" data-anchor-id="region-relative-to-east-midlands"><span class="header-section-number">5.4.3.1.2</span> <strong>Region</strong> (Relative to <strong>East Midlands</strong>)</h5>
<p>Most regions show higher stop-and-search rates than East Midlands, with <strong>London</strong> standing out. For instance: - <strong>London</strong>: Rate ratio of 4.09 (95% CI: 3.7–4.54). - <strong>South East</strong>: Rate ratio of 1.44 (95% CI: 1.28–1.61).</p>
<p>The variation across regions likely reflects differences in policing practices, crime profiles, and population density.</p>
</section>
<section id="ethnicity-relative-to-white" class="level5" data-number="5.4.3.1.3">
<h5 data-number="5.4.3.1.3" class="anchored" data-anchor-id="ethnicity-relative-to-white"><span class="header-section-number">5.4.3.1.3</span> <strong>Ethnicity</strong> (Relative to <strong>White</strong>)</h5>
<p>Ethnic minorities showed significantly different rates of stop and search compared to White individuals: - <strong>Black or Black British</strong>: Rate ratio of 3.02 (95% CI: 2.85–3.2), indicating a 202.2% higher likelihood of being stopped and searched.</p>
</section>
<section id="sex-relative-to-female" class="level5" data-number="5.4.3.1.4">
<h5 data-number="5.4.3.1.4" class="anchored" data-anchor-id="sex-relative-to-female"><span class="header-section-number">5.4.3.1.4</span> <strong>Sex</strong> (Relative to <strong>Female</strong>)</h5>
<ul>
<li><strong>Male</strong>: Rate ratio of 8 (95% CI: 7.55–8.49). Men are significantly more likely to be stopped and searched compared to women.</li>
</ul>
</section>
<section id="age-group-relative-to-age-25" class="level5" data-number="5.4.3.1.5">
<h5 data-number="5.4.3.1.5" class="anchored" data-anchor-id="age-group-relative-to-age-25"><span class="header-section-number">5.4.3.1.5</span> <strong>Age Group</strong> (Relative to Age 25+)</h5>
<ul>
<li><strong>Under 25</strong>: Rate ratio of 1.03 (95% CI: 0.99–1.06), reflecting a slightly increased likelihood for younger individuals.</li>
</ul>
</section>
<section id="reason-for-search-relative-to-non-drug-related" class="level5" data-number="5.4.3.1.6">
<h5 data-number="5.4.3.1.6" class="anchored" data-anchor-id="reason-for-search-relative-to-non-drug-related"><span class="header-section-number">5.4.3.1.6</span> <strong>Reason for Search</strong> (Relative to Non-Drug Related)</h5>
<ul>
<li><strong>Drug-Related</strong>: Rate ratio of 1.77 (95% CI: 1.71–1.84), indicating a substantial increase in stop-and-search likelihood for drug-related reasons.</li>
</ul>
</section>
</section>
</section>
<section id="model-fit-and-diagnostics" class="level3" data-number="5.4.4">
<h3 data-number="5.4.4" class="anchored" data-anchor-id="model-fit-and-diagnostics"><span class="header-section-number">5.4.4</span> Model Fit and Diagnostics</h3>
<ul>
<li><strong>Pseudo R-squared (Cohen’s)</strong>: The pseudo R-squared value of 0.884 indicates that the model explains approximately 88.4% of the variability in stop and search counts, suggesting a strong fit. This high explanatory power supports the model’s validity in identifying and quantifying the associations between stop and search practices and demographic, geographic, and temporal factors.</li>
</ul>
<p>The residual deviance (342,749.3 on 1950 degrees of freedom) indicates a good model fit, with some remaining variability potentially attributable to unobserved factors. The estimated dispersion parameter is 181.8, confirming severe overdispersion; standard errors are scaled accordingly by the Quasi-Poisson family (see Methodology). AIC is not defined for Quasi-Poisson models.</p>
<ul>
<li><strong>Interaction model (ethnicity × financial year)</strong>: To account for part of this overdispersion and allow ethnic disparities to vary over time, we fitted an extended model including an <code>ethnicity × financial_year</code> interaction. The interaction model reduces the dispersion parameter from 181.8 to 174.9 and improves the pseudo R² from 88.4% to 88.8%. An F-test confirms the interaction terms are jointly significant (<em>p</em> &lt; 0.001), indicating that ethnic disparities have shifted meaningfully across financial years. Despite this improvement, the remaining overdispersion (<span class="math inline">\(\hat{\phi} \approx\)</span> 175) reflects heterogeneity at the force level and other unmodelled factors,common feature of aggregate policing data. The Quasi-Poisson framework ensures that all reported confidence intervals and significance tests remain conservative regardless.</li>
</ul>
</section>
<section id="addressing-the-project-questions" class="level3" data-number="5.4.5">
<h3 data-number="5.4.5" class="anchored" data-anchor-id="addressing-the-project-questions"><span class="header-section-number">5.4.5</span> Addressing the Project Questions</h3>
</section>
<section id="addressing-the-project-questions-1" class="level3" data-number="5.4.6">
<h3 data-number="5.4.6" class="anchored" data-anchor-id="addressing-the-project-questions-1"><span class="header-section-number">5.4.6</span> Addressing the Project Questions</h3>
<ol type="1">
<li><p><strong>Do Black People in Metropolitan Areas Experience More Drug Stop and Searches?</strong></p>
<p>To address this question, we analyze the combined effects of ethnicity (Black or Black British), region (London as a proxy for metropolitan area), and reason for search (drug-related):</p>
<ul>
<li><strong>Ethnicity (Black or Black British)</strong>: The rate ratio is 3.02 (95% CI: 2.85–3.2), indicating Black individuals are approximately 3.02 times more likely to be stopped and searched compared to White individuals.</li>
<li><strong>Region (London)</strong>: The rate ratio for London relative to East Midlands is 4.09 (95% CI: 3.7–4.54), confirming that London has far higher search rates than the baseline region.</li>
<li><strong>Reason for Search (Drug-Related)</strong>: The rate ratio is 1.77 (95% CI: 1.71–1.84), indicating drug-related searches are approximately 1.77 times more likely than non-drug-related searches.</li>
</ul>
<p><strong>Combined effect</strong>: The multiplicative rate effect for Black individuals in London during drug-related stops is approximately 21.95 times that for White individuals in the East Midlands for non-drug-related reasons, holding sex and age constant.</p></li>
<li><p><strong>What is the Relationship Between Young People Under 25 and Drug Stops?</strong></p>
<p>For this question, we examine the effects of <strong>age group (under 25)</strong> and <strong>reason for search (drug-related)</strong>:</p>
<ul>
<li><strong>Age Group (Under 25)</strong>: The rate ratio is 1.03 (95% CI: 0.99–1.06), indicating individuals under 25 are approximately 1.03 times more likely to be stopped and searched compared to individuals aged 25 and above.</li>
<li><strong>Reason for Search (Drug-Related)</strong>: The rate ratio is 1.77 (95% CI: 1.71–1.84), suggesting that drug-related searches are approximately 1.77 times more likely than non-drug-related searches.</li>
</ul>
<p><strong>Combined effect</strong>: The multiplicative rate effect for individuals under 25 in drug-related stops is approximately 1.82 times more likely than for older individuals for non-drug-related reasons.</p></li>
</ol>
</section>
<section id="implications-of-findings" class="level3" data-number="5.4.7">
<h3 data-number="5.4.7" class="anchored" data-anchor-id="implications-of-findings"><span class="header-section-number">5.4.7</span> Implications of Findings</h3>
<p>This analysis addresses two primary questions regarding drug-related stop-and-search practices in metropolitan areas:</p>
<ol type="1">
<li><p><strong>Do Black Males under 25 Years of Age in Metropolitan Areas Experience More Drug Stop-and-Searches?</strong></p></li>
<li><p><strong>How Does This Compare to Black Females, White Females, and White Males under 25 in Metropolitan Areas, Specifically When the Reason for Stop and Search is Drug-Related?</strong></p></li>
</ol>
<section id="black-males-under-25-in-metropolitan-areas" class="level4" data-number="5.4.7.1">
<h4 data-number="5.4.7.1" class="anchored" data-anchor-id="black-males-under-25-in-metropolitan-areas"><span class="header-section-number">5.4.7.1</span> 1. Black Males Under 25 in Metropolitan Areas</h4>
<p>The model results indicate that <strong>Black or Black British males under 25 years of age</strong> in metropolitan areas are significantly more likely to experience drug-related stop-and-search encounters. Specifically, this group serves as the reference point for comparison against other demographic groups.</p>
</section>
<section id="comparative-analysis-across-demographic-groups" class="level4" data-number="5.4.7.2">
<h4 data-number="5.4.7.2" class="anchored" data-anchor-id="comparative-analysis-across-demographic-groups"><span class="header-section-number">5.4.7.2</span> 2. Comparative Analysis Across Demographic Groups</h4>
<p>The model’s statistical reference cell is a White female aged 25+ stopped for non-drug reasons in the East Midlands (i.e.&nbsp;the intercept). While useful for model construction, the most <strong>policy-relevant</strong> comparison is between individuals of different ethnicities who share the same sex, age, and search reason,olating the ethnicity effect. The table below re-expresses the combined rate ratios in two ways: first relative to a <strong>comparable White individual</strong> (same sex, age, and reason), then relative to the statistical reference cell.</p>
<div>
<table class="table" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Demographic Profile</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Black/White Ratio (same sex, age, reason)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">vs Reference Cell (White Female, 25+, non-drug)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">Black Male Under 25, Drug Stop</td>
<td style="text-align: center; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">3.02×</td>
<td style="text-align: center; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">44.01×</td>
</tr>
<tr class="even">
<td style="text-align: left;">Black Male 25+, Drug Stop</td>
<td style="text-align: center;">3.02×</td>
<td style="text-align: center;">42.91×</td>
</tr>
<tr class="odd">
<td style="text-align: left; color: rgba(108, 117, 125, 255) !important;">White Male Under 25, Drug Stop</td>
<td style="text-align: center; color: rgba(108, 117, 125, 255) !important;">---</td>
<td style="text-align: center; color: rgba(108, 117, 125, 255) !important;">14.56×</td>
</tr>
<tr class="even">
<td style="text-align: left; color: rgba(108, 117, 125, 255) !important;">White Male 25+, Drug Stop</td>
<td style="text-align: center; color: rgba(108, 117, 125, 255) !important;">---</td>
<td style="text-align: center; color: rgba(108, 117, 125, 255) !important;">14.2×</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Black Female 25+, Drug Stop</td>
<td style="text-align: center;">3.02×</td>
<td style="text-align: center;">5.36×</td>
</tr>
<tr class="even">
<td style="text-align: left; color: rgba(108, 117, 125, 255) !important;">White Female 25+, Drug Stop</td>
<td style="text-align: center; color: rgba(108, 117, 125, 255) !important;">---</td>
<td style="text-align: center; color: rgba(108, 117, 125, 255) !important;">1.77×</td>
</tr>
</tbody>
</table>


</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>Because this is a main-effects (additive on the log scale) model, the <strong>ethnicity multiplier is constant</strong>: a Black individual is 3.02<span class="math inline">\(\times\)</span> more likely to be stopped than a White individual of the same sex, age group, and search reason. This 3.02<span class="math inline">\(\times\)</span> factor is the central measure of racial disparity.</p></li>
<li><p>A <strong>Black male under 25</strong> stopped for drug-related reasons has a combined rate ratio of <strong>44.01</strong> relative to the reference cell,t <strong>3.02<span class="math inline">\(\times\)</span></strong> relative to a White male under 25 stopped for the same reason. The difference between 44.01 and 3.02 is entirely explained by the sex (8<span class="math inline">\(\times\)</span>), age (1.03<span class="math inline">\(\times\)</span>), and drug (1.77<span class="math inline">\(\times\)</span>) effects, which affect Black and White individuals equally in this model.</p></li>
<li><p><strong>White Males Under 25 for Drugs</strong> have a rate ratio of 14.56 versus the reference cell, highlighting that sex and drug effects are substantial independent of ethnicity,t the <strong>ethnicity gap</strong> roughly triples the rate for Black individuals in every combination.</p></li>
</ul>
</section>
</section>
<section id="policy-implications" class="level3" data-number="5.4.8">
<h3 data-number="5.4.8" class="anchored" data-anchor-id="policy-implications"><span class="header-section-number">5.4.8</span> Policy Implications</h3>
<p>The identified disparities necessitate targeted interventions to ensure equitable policing practices:</p>
<ol type="1">
<li><strong>Policy Review and Reform:</strong>
<ul>
<li><strong>Implement Equitable Policing Guidelines:</strong> Develop and enforce guidelines that minimize racial and gender biases in stop-and-search operations.</li>
<li><strong>Data Transparency:</strong> Mandate comprehensive data collection and public reporting on stop-and-search encounters to monitor and address disparities.</li>
</ul></li>
<li><strong>Training and Awareness:</strong>
<ul>
<li><strong>Bias Training:</strong> Enhance training programs for law enforcement to recognize and mitigate unconscious biases that contribute to disproportionate targeting of specific demographic groups.</li>
<li><strong>Cultural Competency:</strong> Foster cultural competency among police officers to improve interactions with diverse communities.</li>
</ul></li>
<li><strong>Community Engagement:</strong>
<ul>
<li><strong>Build Trust:</strong> Engage with communities, particularly among young Black males, to build trust and cooperation between law enforcement and the populations they serve.</li>
<li><strong>Feedback Mechanisms:</strong> Establish channels for community members to provide feedback and report instances of discriminatory practices without fear of retaliation.</li>
</ul></li>
</ol>
<p>By addressing these areas, policymakers and law enforcement agencies can work towards more fair and just policing strategies, ensuring that stop-and-search practices do not disproportionately affect specific demographic groups and that all individuals are treated equitably under the law.</p>
</section>
</section>
<section id="random-forest-model-machine-learning-approach" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="random-forest-model-machine-learning-approach"><span class="header-section-number">5.5</span> Random Forest Model: Machine Learning Approach</h2>
<p><img src="results_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
<p>A random forest model was used to identify the most influential factors associated with total stop-and-search activity across financial years, regions, and demographic groups. This approach complements the regression analysis by revealing complex, non-linear relationships between predictors and total searches. The random forest was trained on demographic and contextual variables, including <strong>financial year</strong>, <strong>region</strong>, <strong>ethnicity</strong>, <strong>sex</strong>, <strong>age group</strong>, <strong>reason for search</strong>, and <strong>population size</strong>, to determine the relative importance of each factor in predicting the total number of stop-and-searches. The variable importance measures (based on %IncMSE) highlight key factors that influence stop-and-search volume and allow an in-depth exploration of the project’s objectives.</p>
<section id="variable-importance-and-interpretation" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="variable-importance-and-interpretation"><span class="header-section-number">5.5.1</span> Variable Importance and Interpretation</h3>
<p>The variable importance plot (Figure X) shows each predictor’s contribution to the model, measured by % Increase in Mean Squared Error (%IncMSE). Key findings from the random forest analysis include:</p>
<ol type="1">
<li><strong>Sex</strong>:
<ul>
<li><strong>Sex</strong> emerged as the most influential predictor (%IncMSE = 61.8), the single strongest driver of search volume in the model. Consistent with the regression findings, males are disproportionately represented in stop-and-search activity. This alignment across model types underscores the persistent gender gap in policing.</li>
</ul></li>
<li><strong>Population</strong>:
<ul>
<li><strong>Population size</strong> was the second most important predictor (%IncMSE = 36.8). Areas with larger populations experience higher total search counts, reflecting the concentration of searches in densely populated regions.</li>
</ul></li>
<li><strong>Region</strong>:
<ul>
<li><strong>Region</strong> also displayed a high %IncMSE, suggesting that geographic location strongly influences stop-and-search activity. This regional variation likely reflects different policing strategies and priorities across England and Wales. The substantial impact of region on search volume suggests that certain areas are more intensely policed, which may be related to local crime rates, population density, or policy differences.</li>
</ul></li>
<li><strong>Ethnicity</strong>:
<ul>
<li><strong>Ethnicity</strong> emerged as an influential factor, with notable %IncMSE values. Within the random forest model, Black or Black British individuals were particularly associated with higher search counts, reflecting the model’s capacity to capture ethnic disparities in policing. The importance of ethnicity aligns with the project’s focus on identifying demographic disparities in stop-and-search practices, confirming that specific ethnic groups are more frequently targeted in police searches.</li>
</ul></li>
<li><strong>Financial Year and Reason for Search</strong>:
<ul>
<li><strong>Financial year</strong> and <strong>reason for search</strong> also contributed to the prediction of total searches, though to a lesser extent than population, sex, and region. The financial year variable’s influence suggests temporal changes in policing activity, potentially linked to policy adjustments or shifts in crime prevention focus over time. <strong>Drug-related stops</strong> (indicated by the reason for search variable) were also predictive of higher search counts, suggesting that specific search reasons contribute to variation in stop-and-search volume.</li>
</ul></li>
<li><strong>Age Group</strong>:
<ul>
<li><strong>Age group</strong> exhibited a low and even negative %IncMSE, indicating that age group alone may not meaningfully enhance prediction accuracy in this model. This contrasts with the regression analysis, where age group had a positive association with search counts. The random forest results suggest that age might interact with other factors (like ethnicity or reason for search) rather than being a primary predictor of search volume independently.</li>
</ul></li>
</ol>
</section>
<section id="implications-for-project-objectives" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="implications-for-project-objectives"><span class="header-section-number">5.5.2</span> Implications for Project Objectives</h3>
<p>The random forest model findings align with the project’s objectives, providing detailed insights into factors influencing total stop-and-search counts and validating key areas of demographic disparity. The high importance of <strong>sex</strong>, <strong>population</strong>, and <strong>region</strong> reveals structural factors that drive search volumes across England and Wales, with clear implications for regional and demographic disparities in policing. The consistent influence of <strong>ethnicity</strong> across both the random forest and regression models underscores the model’s reliability in identifying areas where certain groups are disproportionately affected by stop-and-search practices.</p>
<p>In summary, the random forest analysis provides a robust exploration of the factors driving total stop-and-search volume. By identifying sex, population, region, and ethnicity as major predictors, the model highlights demographic and regional differences in policing practices. This evidence-based approach supports the project’s goal to uncover disparities and guide recommendations for more equitable policing policies across demographic groups.</p>
<hr>
</section>
</section>
<section id="sec-trend" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="sec-trend"><span class="header-section-number">5.6</span> Five-Year Disparity Trend</h2>
<p>The sections above present the pooled model results. Here we examine how the <strong>adjusted disparity</strong>, controlling for region, sex, age, and reason for search, has evolved year by year over the five-year period 2020/21–2024/25, using pre-computed per-year Quasi-Poisson models.</p>
<div>
<table class="table" data-quarto-postprocess="true">
<caption>Per-year adjusted IRR for Black vs White individuals (Quasi-Poisson)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Financial Year</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Adjusted IRR</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2020/21</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: left;">(2.76–3.26)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021/22</td>
<td style="text-align: right;">2.86</td>
<td style="text-align: left;">(2.61–3.14)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022/23</td>
<td style="text-align: right;">2.90</td>
<td style="text-align: left;">(2.63–3.2)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2023/24</td>
<td style="text-align: right;">3.08</td>
<td style="text-align: left;">(2.77–3.41)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024/25</td>
<td style="text-align: right;">3.33</td>
<td style="text-align: left;">(3–3.7)</td>
</tr>
</tbody>
</table>


</div>
<p><img src="results_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
<p>The adjusted IRR for Black individuals relative to White individuals shows a <strong>U-shaped trend</strong>: falling slightly in 2021/22 (IRR = 2.86) and 2022/23 (IRR = 2.9) before rising sharply to 3.08 in 2023/24 and reaching 3.33 (95% CI: 3–3.7) in 2024/25. The 2024/25 figure is statistically distinguishable from the 2020/21 baseline (IRR = 3; 95% CI: 2.76–3.26), indicating a real and significant worsening of the adjusted disparity over the five-year period.</p>
<p>This worsening is all the more striking because it occurs against a backdrop of <strong>falling overall search volumes</strong>: raw Black search rates per 1,000 population have declined substantially since 2020/21, but have fallen more slowly than White rates, resulting in a widening relative gap once demographic and geographic composition is held constant.</p>
<hr>
</section>
<section id="sec-regional" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="sec-regional"><span class="header-section-number">5.7</span> Regional Force Rankings</h2>
<div>
<table class="table" data-quarto-postprocess="true">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Stop and search rates and Black/White disparity ratios by region (2020/21–2024/25 pooled)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Region</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Black rate (per 100k)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">White rate (per 100k)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Black/White ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">South West</td>
<td style="text-align: right; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">12.2</td>
<td style="text-align: right; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">2.4</td>
<td style="text-align: right; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">5.09</td>
</tr>
<tr class="even">
<td style="text-align: left;">West Midlands</td>
<td style="text-align: right;">15.4</td>
<td style="text-align: right;">3.7</td>
<td style="text-align: right;">4.17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">East Midlands</td>
<td style="text-align: right;">10.9</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">4.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">East of England</td>
<td style="text-align: right;">12.9</td>
<td style="text-align: right;">3.4</td>
<td style="text-align: right;">3.81</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South East</td>
<td style="text-align: right;">16.3</td>
<td style="text-align: right;">4.5</td>
<td style="text-align: right;">3.63</td>
</tr>
<tr class="even">
<td style="text-align: left;">London</td>
<td style="text-align: right;">24.7</td>
<td style="text-align: right;">6.8</td>
<td style="text-align: right;">3.62</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wales</td>
<td style="text-align: right;">13.6</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">3.44</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yorkshire and The Humber</td>
<td style="text-align: right;">14.3</td>
<td style="text-align: right;">4.5</td>
<td style="text-align: right;">3.18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North West</td>
<td style="text-align: right;">37.6</td>
<td style="text-align: right;">16.3</td>
<td style="text-align: right;">2.31</td>
</tr>
<tr class="even">
<td style="text-align: left;">North East</td>
<td style="text-align: right;">12.9</td>
<td style="text-align: right;">6.6</td>
<td style="text-align: right;">1.95</td>
</tr>
</tbody>
</table>


</div>
<p><img src="results_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
<p>The regional analysis reveals striking variation in the unadjusted Black/White disparity. The <strong>South West</strong> has the highest ratio at 5.09×, substantially exceeding London (3.62×). This is notable given that London is typically assumed to be the focal point of ethnic disproportionality. The North East has the lowest ratio (1.95×), though it remains above parity. The South West anomaly is discussed further in the Discussion chapter.</p>
<p>The North West shows extremely high absolute rates for all ethnic groups (Black: 37.6 per 100,000; White: 16.3 per 100,000), suggesting a general pattern of intensive policing rather than ethnicity-specific targeting, reflected in its relatively lower ratio of 2.31×.</p>
<hr>
</section>
<section id="sec-outcomes" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="sec-outcomes"><span class="header-section-number">5.8</span> Outcome Disparity by Ethnicity</h2>
<p>A key indicator of whether stop and search powers are deployed appropriately is the <strong>post-search outcome distribution</strong>. If the evidential threshold for initiating a search is genuinely equivalent across ethnic groups, we would expect broadly similar outcome profiles.</p>
<div>
<table class="table" data-quarto-postprocess="true">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Post-search outcome distribution by ethnicity (2020/21–2024/25, %, selected outcomes)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">ethnicity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Arrest (%)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Community Resolution (%)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No Further Action (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Asian</td>
<td style="text-align: right;">12.4</td>
<td style="text-align: right;">9.5</td>
<td style="text-align: right;">68.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Black</td>
<td style="text-align: right;">16.0</td>
<td style="text-align: right;">8.7</td>
<td style="text-align: right;">68.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mixed</td>
<td style="text-align: right;">16.0</td>
<td style="text-align: right;">10.6</td>
<td style="text-align: right;">65.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other</td>
<td style="text-align: right;">15.2</td>
<td style="text-align: right;">9.6</td>
<td style="text-align: right;">68.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">White</td>
<td style="text-align: right;">13.3</td>
<td style="text-align: right;">7.9</td>
<td style="text-align: right;">69.6</td>
</tr>
</tbody>
</table>


</div>
<p><img src="results_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
<p>Across all ethnic groups, <strong>No Further Action (NFA)</strong> is by far the most common outcome, indicating that the majority of searches do not result in any enforcement action. The NFA rate for Black individuals (68.9%) is marginally lower than for White individuals (69.6%), which might appear reassuring. However, the <strong>arrest rate</strong> tells a different story: Black individuals have one of the highest arrest rates at 16% (tied with Mixed), compared to 13.3% for White individuals and 12.4% for Asian individuals. This differential is consistent with searches against Black individuals being somewhat more likely to yield enforcement action; yet given the substantially higher stop rate, it also implies that a large number of Black individuals are searched without justification. The implications of this pattern are discussed in the Discussion chapter.</p>
<hr>
</section>
<section id="sec-age-ethnicity" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="sec-age-ethnicity"><span class="header-section-number">5.9</span> Age by Ethnicity Interaction</h2>
<div>
<table class="table" data-quarto-postprocess="true">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th colspan="6" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Percentage of stops involving individuals under 25, by ethnicity and year (%)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Financial Year</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Asian</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Black</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mixed</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Other</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">White</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2020/21</td>
<td style="text-align: right;">58.7</td>
<td style="text-align: right;">60.8</td>
<td style="text-align: right;">63.4</td>
<td style="text-align: right;">55.1</td>
<td style="text-align: right;">50.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021/22</td>
<td style="text-align: right;">56.7</td>
<td style="text-align: right;">58.0</td>
<td style="text-align: right;">63.8</td>
<td style="text-align: right;">52.3</td>
<td style="text-align: right;">48.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022/23</td>
<td style="text-align: right;">56.3</td>
<td style="text-align: right;">59.5</td>
<td style="text-align: right;">62.3</td>
<td style="text-align: right;">51.1</td>
<td style="text-align: right;">48.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">2023/24</td>
<td style="text-align: right;">53.6</td>
<td style="text-align: right;">57.7</td>
<td style="text-align: right;">60.9</td>
<td style="text-align: right;">49.4</td>
<td style="text-align: right;">45.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024/25</td>
<td style="text-align: right;">50.9</td>
<td style="text-align: right;">55.1</td>
<td style="text-align: right;">60.2</td>
<td style="text-align: right;">47.6</td>
<td style="text-align: right;">43.8</td>
</tr>
</tbody>
</table>


</div>
<p><img src="results_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid" width="672"></p>
<p>Black individuals who are stopped and searched are more likely to be under 25 than any other ethnic group. In 2024/25, 55.1% of all searches targeting Black individuals involved someone under 25, compared with 43.8% for White individuals. This age concentration has remained broadly stable over the five years, suggesting that the compounded disadvantage faced by young Black men in stop and search encounters is a persistent structural feature rather than a short-term fluctuation.</p>
<hr>
</section>
<section id="sec-reason-skew" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="sec-reason-skew"><span class="header-section-number">5.10</span> Racial Skew by Search Reason</h2>
<p>Not all search reasons carry the same racial disparity. This section asks: <strong>which reason for search shows the greatest Black/White rate gap?</strong> Rates are computed per 1,000 population using the 2021 Census as denominator, pooled across all five years.</p>
<div>
<table class="table" data-quarto-postprocess="true">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Black/White stop-and-search rate ratio by reason (pooled 2020/21–2024/25)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Reason for Search</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Black rate (per 1,000)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">White rate (per 1,000)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Black / White ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">Anticipation of Violence</td>
<td style="text-align: right; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">1.88</td>
<td style="text-align: right; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">0.24</td>
<td style="text-align: right; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">7.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">Offensive Weapons</td>
<td style="text-align: right;">26.91</td>
<td style="text-align: right;">3.88</td>
<td style="text-align: right;">6.93</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Terrorism Act 2000 section 43</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">6.76</td>
</tr>
<tr class="even">
<td style="text-align: left;">Firearms</td>
<td style="text-align: right;">1.21</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">5.48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stolen Property</td>
<td style="text-align: right;">13.64</td>
<td style="text-align: right;">2.96</td>
<td style="text-align: right;">4.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">Drugs</td>
<td style="text-align: right;">81.23</td>
<td style="text-align: right;">19.00</td>
<td style="text-align: right;">4.28</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: right;">1.76</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">2.79</td>
</tr>
<tr class="even">
<td style="text-align: left;">Going Equipped</td>
<td style="text-align: right;">5.01</td>
<td style="text-align: right;">2.74</td>
<td style="text-align: right;">1.83</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Criminal Damage</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">1.14</td>
</tr>
</tbody>
</table>


</div>
<p><img src="results_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid" width="672"></p>
<p>The search reason with the highest racial disparity is <strong>Anticipation of Violence</strong> (Black/White ratio: 7.94×). Drug-related stops carry a ratio of 4.28×, while searches for offensive weapons or articles for use in crime show a ratio of 6.93×. The fact that disparity is pronounced across multiple search reasons, not just drugs, indicates that the over-representation of Black individuals in stop and search cannot be attributed to a single enforcement focus. Every major search category shows a Black/White rate gap well above parity.</p>
<hr>
</section>
<section id="sec-missing" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="sec-missing"><span class="header-section-number">5.11</span> Missing Ethnicity Data: Systematic Patterns</h2>
<p>Around 1 in 10 stop and search records does not include a self-defined ethnicity. The primary reason for this is that individuals are not legally required to disclose their ethnicity during a stop and search: the Home Office notes that “good quality data for self-defined ethnicity is reliant on the individual who is stopped and searched to provide this information, which they are not required to tell the police officer” <span class="citation" data-cites="govuk_police_2024">(<a href="references.html#ref-govuk_police_2024" role="doc-biblioref">(GOV.UK), 2024</a>)</span>. In addition, transitions between recording systems within individual forces can cause temporary spikes in missing records. Variation in missing rates across forces may therefore reflect differences in how often individuals decline to state their ethnicity, local recording practices, or system changes;e factors cannot be distinguished from the data alone.</p>
<div>
<table class="table" data-quarto-postprocess="true">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
National missing ethnicity rate by year
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Financial Year</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total Records</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Missing Ethnicity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">% Missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2020/21</td>
<td style="text-align: right;">102,393</td>
<td style="text-align: right;">24,918</td>
<td style="text-align: right;">24.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021/22</td>
<td style="text-align: right;">92,844</td>
<td style="text-align: right;">22,116</td>
<td style="text-align: right;">23.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022/23</td>
<td style="text-align: right;">102,978</td>
<td style="text-align: right;">25,570</td>
<td style="text-align: right;">24.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">2023/24</td>
<td style="text-align: right;">107,668</td>
<td style="text-align: right;">26,475</td>
<td style="text-align: right;">24.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024/25</td>
<td style="text-align: right;">114,176</td>
<td style="text-align: right;">27,543</td>
<td style="text-align: right;">24.1</td>
</tr>
</tbody>
</table>
<table class="table" data-quarto-postprocess="true">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Forces with highest persistent missing ethnicity (mean across all available years)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Police Force</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Region</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean % Missing</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max % Missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">London, City of</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">London</td>
<td style="text-align: right; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">41.6</td>
<td style="text-align: right; font-weight: bold; background-color: rgba(255, 243, 205, 255) !important;">44.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nottinghamshire</td>
<td style="text-align: left;">East Midlands</td>
<td style="text-align: right;">33.5</td>
<td style="text-align: right;">39.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Avon &amp; Somerset</td>
<td style="text-align: left;">South West</td>
<td style="text-align: right;">32.0</td>
<td style="text-align: right;">33.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thames Valley</td>
<td style="text-align: left;">South East</td>
<td style="text-align: right;">30.3</td>
<td style="text-align: right;">33.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Essex</td>
<td style="text-align: left;">East of England</td>
<td style="text-align: right;">29.8</td>
<td style="text-align: right;">33.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Humberside</td>
<td style="text-align: left;">Yorkshire and The Humber</td>
<td style="text-align: right;">29.6</td>
<td style="text-align: right;">36.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Greater Manchester</td>
<td style="text-align: left;">North West</td>
<td style="text-align: right;">28.6</td>
<td style="text-align: right;">34.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Devon &amp; Cornwall</td>
<td style="text-align: left;">South West</td>
<td style="text-align: right;">28.2</td>
<td style="text-align: right;">39.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gwent</td>
<td style="text-align: left;">Wales</td>
<td style="text-align: right;">28.0</td>
<td style="text-align: right;">38.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">North Yorkshire</td>
<td style="text-align: left;">Yorkshire and The Humber</td>
<td style="text-align: right;">27.5</td>
<td style="text-align: right;">34.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kent</td>
<td style="text-align: left;">South East</td>
<td style="text-align: right;">27.4</td>
<td style="text-align: right;">31.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lancashire</td>
<td style="text-align: left;">North West</td>
<td style="text-align: right;">27.2</td>
<td style="text-align: right;">30.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Leicestershire</td>
<td style="text-align: left;">East Midlands</td>
<td style="text-align: right;">27.2</td>
<td style="text-align: right;">32.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">North Wales</td>
<td style="text-align: left;">Wales</td>
<td style="text-align: right;">27.0</td>
<td style="text-align: right;">40.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South Yorkshire</td>
<td style="text-align: left;">Yorkshire and The Humber</td>
<td style="text-align: right;">26.9</td>
<td style="text-align: right;">28.4</td>
</tr>
</tbody>
</table>


</div>
<p><img src="results_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid" width="672"></p>
<p>The missing ethnicity rate is far from uniformly distributed. <strong>London, City of</strong> has the highest average missing rate at 41.6%, and 30 forces average above 20% missing across the study period. Forces with persistently high rates of missing self-defined ethnicity are effectively absent from ethnicity-specific analyses, which limits the extent to which disparity estimates can be compared equally across all forces. Whether this concentration reflects recording practice differences, system transitions, or higher rates of non-disclosure in particular areas cannot be determined from the available data.</p>


<div id="refs" class="references csl-bib-body" role="list" style="display: none">
<div id="ref-govuk_police_2024" class="csl-entry" role="listitem">
(GOV.UK), H. O. (2024) <span>“Police powers and procedures: <span>Stop</span> and search and arrests, <span>England</span> and <span>Wales</span>, year ending 31 <span>March</span> 2023 (second edition),”</span> National {Statistics} [Online]. Available at <a href="https://www.gov.uk/government/statistics/stop-and-search-and-arrests-year-ending-march-2023/police-powers-and-procedures-stop-and-search-and-arrests-england-and-wales-year-ending-31-march-2023">https://www.gov.uk/government/statistics/stop-and-search-and-arrests-year-ending-march-2023/police-powers-and-procedures-stop-and-search-and-arrests-england-and-wales-year-ending-31-march-2023</a> (Accessed 29 March 2024).
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./methodology.html" class="pagination-link" aria-label="Methodology">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Methodology</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./discussion.html" class="pagination-link" aria-label="Discussion Section">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Discussion Section</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>