import { motion } from 'framer-motion'

export default function Methodology() {
  return (
    <section className="bg-apple-dark px-6 py-32 text-white">
      <div className="mx-auto max-w-5xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
        >
          <h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">
            How This Was Done
          </h2>
          <p className="mt-4 max-w-2xl text-apple-silver">
            This analysis follows rigorous statistical methodology and is fully reproducible.
          </p>
        </motion.div>

        <div className="mt-16 grid gap-10 sm:grid-cols-3">
          {[
            {
              heading: 'Data',
              body: 'Home Office stop-and-search open data tables, financial years 2020/21 to 2024/25 (556,186 records). Population denominators from ONS Census 2021. British Transport Police and vehicle-only searches excluded.',
            },
            {
              heading: 'Model',
              body: 'Quasi-Poisson generalised linear model with log population offset. Predictors: financial year, region, ethnicity, sex, age group (binary: under 25), and reason for search (binary: drugs). Overdispersion confirmed (φ = 181); quasi-Poisson used for robust standard errors.',
            },
            {
              heading: 'QA',
              body: 'All totals validated against published GOV.UK headline figures. Our totals are 1–6% lower (expected, due to exclusions). Every figure in this dashboard and the accompanying report is generated by code and can be reproduced from a single script.',
            },
          ].map(({ heading, body }) => (
            <motion.div
              key={heading}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <p className="text-xs font-semibold uppercase tracking-widest text-apple-silver mb-3">
                {heading}
              </p>
              <p className="text-sm leading-relaxed text-apple-mist">{body}</p>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mt-16 flex flex-wrap items-center gap-4"
        >
          <a
            href="/report/"
            className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-semibold text-apple-dark transition hover:bg-apple-mist"
          >
            Read the full report
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
            </svg>
          </a>
          <a
            href="https://github.com/M2LabOrg/unjust-analysis"
            className="inline-flex items-center gap-2 rounded-full border border-white/20 px-6 py-3 text-sm font-semibold text-white transition hover:border-white/60"
            target="_blank"
            rel="noopener noreferrer"
          >
            View code on GitHub
          </a>
        </motion.div>
      </div>
    </section>
  )
}
